import { Geist, Geist_Mono, Great_Vibes } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import Navbar from "@/components/Navbar";
import { UserProvider } from "@/context/UserContext";
import { LikedProvider } from "@/context/LikedContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  weight: ["400"], // Specify the font weights you need
  subsets: ["latin"], // Specify the subsets to load
});

export const metadata = {
  title: "Gordana & Petar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${greatVibes.variable}`}
      >
        <UserProvider>
          <LikedProvider>
            <Navbar></Navbar>
            {children}
            <Toaster
              position="top-center"
              toastOptions={{
                style: {
                  background: "rgb(230 228 221 / 70%)",
                  backdropFilter: "blur(15px)",
                  color: "222",
                },
              }}
            ></Toaster>
          </LikedProvider>
        </UserProvider>
      </body>
    </html>
  );
}
